### PR TITLE
Normalizing warranty data being returned

### PR DESCRIPTION
**Pull request by ketiko**

### CODE REVIEW

**Comment by braindev** [comment]
Looking at the `Gemfile.lock` why don't we try a bundle update on `eventmachine`?

**Comment by braindev** [comment]
I'm not sure why we have the gemfile.lock file committed at all.

http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/
http://viget.com/extend/bundler-best-practices

**Comment by ketiko** [comment]
@braindev Eventmachine isn't directly included and hence doesn't change with `bundle update eventmachine`.  It's only there as a dependency of a dependency.

**Comment by braindev** [comment]
I'll merge but this might be worth coming back to some day.

**Pull request merged**
